[tox]
minversion = 3.21.0

# this isn't a formal Python package
skipsdist = true    

[testenv]
setenv =
    SOURCES = boot.py code.py

[testenv:fmt]
deps = 
    black
    isort

commands = 
    black {env:SOURCES}
    isort --profile black {env:SOURCES}
